version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: yarn && yarn build

workflows:
  version: 2
  build:
    jobs:
      - build
